server:
  port: 8080
  address: 0.0.0.0

spring:
  datasource:
    url: jdbc:mysql://poosoap-mysql:3306/poosoap?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
    username: poosoap-user
    password: poosoapUser1!
    driver-class-name: com.mysql.cj.jdbc.Driver