server:
  port: 8080
  address: 0.0.0.0

jpa:
  hibernate:
    ddl-auto: update
    naming:
      implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
      physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
  show-sql: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/poosoap?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
    username: poosoap-user
    password: poosoapUser1!
    driver-class-name: com.mysql.cj.jdbc.Driver
